/*
 * CurrencyConverter
 * Currency converter based on the Frankfurter.APP
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package app.frankfurter.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets CurCodes
 */
public enum CurCodes {
  AUD("AUD"),
  BGN("BGN"),
  BRL("BRL"),
  CAD("CAD"),
  CHF("CHF"),
  CNY("CNY"),
  CZK("CZK"),
  DKK("DKK"),
  EUR("EUR"),
  GBP("GBP"),
  HKD("HKD"),
  HRK("HRK"),
  HUF("HUF"),
  IDR("IDR"),
  ILS("ILS"),
  INR("INR"),
  ISK("ISK"),
  JPY("JPY"),
  KRW("KRW"),
  MXN("MXN"),
  MYR("MYR"),
  NOK("NOK"),
  NZD("NZD"),
  PHP("PHP"),
  PLN("PLN"),
  RON("RON"),
  RUB("RUB"),
  SEK("SEK"),
  SGD("SGD"),
  THB("THB"),
  TRY("TRY"),
  USD("USD"),
  ZAR("ZAR");

  private String value;

  CurCodes(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CurCodes fromValue(String text) {
    for (CurCodes b : CurCodes.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
