/*
 * CurrencyConverter
 * Currency converter based on the Frankfurter.APP
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package app.frankfurter.api.client;

import java.util.Objects;
import java.util.Arrays;
import app.frankfurter.api.client.Rates;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Rate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-02T15:57:16.798025+01:00[Europe/Zurich]")
public class Rate {
  @JsonProperty("amount")
  private Double amount = null;

  @JsonProperty("base")
  private String base = null;

  @JsonProperty("date")
  private String date = null;

  @JsonProperty("rates")
  private Rates rates = null;

  public Rate amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }

  public Rate base(String base) {
    this.base = base;
    return this;
  }

   /**
   * Get base
   * @return base
  **/
  public String getBase() {
    return base;
  }

  public void setBase(String base) {
    this.base = base;
  }

  public Rate date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public Rate rates(Rates rates) {
    this.rates = rates;
    return this;
  }

   /**
   * Get rates
   * @return rates
  **/
  public Rates getRates() {
    return rates;
  }

  public void setRates(Rates rates) {
    this.rates = rates;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rate rate = (Rate) o;
    return Objects.equals(this.amount, rate.amount) &&
        Objects.equals(this.base, rate.base) &&
        Objects.equals(this.date, rate.date) &&
        Objects.equals(this.rates, rate.rates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, base, date, rates);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rate {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    base: ").append(toIndentedString(base)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    rates: ").append(toIndentedString(rates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
