name: E2E-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -DtestEnvironment=E2E