RestClients:
  #Currency converter based on the Frankfurter.APP
  Currency Converter API (CurrencyConverter):
    UUID: f6097886-ec23-421a-8264-e8782f59723e
    Url: https://api.frankfurter.app/
    Icon: res:/webContent/icons/curConverterSmall.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
